name: rmd-env

channels:
  - conda-forge
  - bioconda
  - pwwang

dependencies:
  - r-base>=4.3.0
  - r-rmarkdown
  - r-ggplot2
  - r-codetools
  - r-tidyverse
  - r-prettydoc
  - r-viridis
  - r-hrbrthemes
  - r-ggthemes
  - r-RColorBrewer
  - r-scales
  - r-segmented
  - r-dplyr
  - r-xlsx
  - r-rmdformats
  - r-plotly
  - r-gridExtra
  - r-ape
  - r-vegan
  - r-ggvenndiagram
  - r-venndiagram
  - r-ggforce
  - r-ggdendro
  - r-pheatmap
  - r-heatmaply
  - r-readxl
  - r-cowplot
  - r-picante
  - r-ggalluvial
  - r-ggnewscale
  - r-ggraph
  - r-ggrepel
  - r-ggbeeswarm
  - r-gggenes
  - r-ggcorrplot
  - r-ggnetwork
  - r-factominer
  - r-factoextra
  - pandoc
  - r-beeswarm
  - r-ade4
  - r-bookdown
  - r-circlize
  - r-igraph
  - r-dbi
  - r-ggfittext
  - r-dendextend
  - r-devtools
  - r-ggfx
  - r-ggpubr
  - r-ggsignif
  - r-htmltools
  - r-htmlwidgets
  - r-rstatix
  - r-tidygraph
  - bioconductor-phyloseq
  - bioconductor-biostrings
  - bioconductor-complexheatmap
  - bioconductor-genomeinfodb
  - bioconductor-microbiome
  - bioconductor-phyloseq
  - bioconductor-annotationdbi
  - bioconductor-biocfilecache
  - bioconductor-keggrest
  - bioconductor-org.hs.eg.db
  - r-filelock
  - r-patchwork
  - r-plogr
  - r-rsqlite
  - r-shadowtext
  - r-xml
  - cairo
  - r-cairo